resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/develop
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
  - task: DotNetCoreCLI@2
    displayName: Build project
    inputs:
      projects: '**/SampleFunctionApp.csproj'
  - task: ArchiveFiles@2
    displayName: Archive files
    inputs:
      rootFolderOrFile: publish_output/
      includeRootFolder: false
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
